# YouTube Analytics Report
#
# DATA
# USvideos.csv: 40,949 rows -> 6,351 unique videos (max-views row kept per video_id)
# viral = views > 1,474,750 (75th percentile): 1,588 viral (25%), 4,763 non-viral
# Dataset contains trending videos only, so "viral" is relative to this set
# duration is not in the dataset; title_length and days_since_publish were derived
#
# 1. REGRESSION (Linear Regression, 80/20 split, test n=1,271)
# | Metric        | Test set  | 5-fold CV (mean / var) |
# |---------------|-----------|------------------------|
# | R2            | 0.7714    | 0.7424 / 0.0048        |
# | MSE           | 1.039e13  |                        |
# | RMSE          | 3.224e6   |                        |
# | MAE           | 1.106e6   |                        |
# Key predictors (coef per std): likes +7.46e6, dislikes +3.07e6, comment_count -3.74e6 (collinear with likes)
# Channel effects: Universal Pictures +5.4e6, AsapSCIENCE +3.4e6, Marvel Entertainment +3.0e6
# title_length and days_since_publish are negligible
#
# 2. CLASSIFICATION (Logistic Regression, 80/20 stratified split)
# | Metric    | Test set | 5-fold CV ROC-AUC (mean / var) |
# |-----------|----------|--------------------------------|
# | Accuracy  | 0.9119   | StandardScaler: 0.9481 / 4.5e-05 |
# | Precision | 0.9087   | MinMaxScaler:   0.8065 / 4.6e-04 |
# | Recall    | 0.7201   |                                |
# | F1        | 0.8035   |                                |
# | ROC-AUC   | 0.9427   |                                |
# Key predictors (coef): likes +9.43, dislikes +3.73; channels: Warner Bros. +2.11, Saturday Night Live +1.74, Tasty +1.65
# Negative channel effects: IISuperwomanII -2.17, jacksfilms -2.10
# comment_count, title_length, days_since_publish: |coef| < 0.5
#
# 3. HYPOTHESIS TESTING (Welch t-test, views of above-median vs below-median feature group, one-sided)
# | Feature       | p-value  | Decision (alpha=0.05) |
# |---------------|----------|-----------------------|
# | likes         | 4.8e-73  | reject H0             |
# | dislikes      | 1.3e-76  | reject H0             |
# | comment_count | 1.4e-68  | reject H0             |
# Hypothesis supported: higher likes, dislikes and comment counts go with significantly higher views
# Correlation with views: likes 0.83, comment_count 0.57, dislikes 0.44
#
# 4. SCALING
# StandardScaler vs MinMaxScaler: identical for Linear Regression, MinMaxScaler is much worse for Logistic Regression
# (ROC-AUC 0.807 vs 0.948); use StandardScaler
#
# 5. BUSINESS RECOMMENDATIONS
# - Engagement (likes above all) is the strongest signal of views and virality in both models; it follows from viewership, so use it to spot working content, not as a proven cause
# - Titles: viral rate falls as title length grows (<=30 chars 28.6%, 31-50 26.0%, 51-70 23.7%, >70 20.9%); keep titles under ~50 characters
# - Categories: highest viral rate in category_id 20 (46.6%), 10 (44.6%), 1 (41.6%); lowest in 25 (5.8%) and 27 (9.2%)
# - Channels: established studio channels carry a large positive effect; smaller channels depend on engagement
# - Optimal video length cannot be determined from this dataset (no duration column)
#
# 6. PLOTS (generated by the task scripts)
# task2.py: views histogram, likes vs views scatter, correlation heatmap
# task5.py: top-15 coefficients
# task6.py: confusion matrix, ROC curve
# task7.py: logistic regression feature importance